import type { Request, Response } from 'express';

export const uploadImage = (req: Request, res: Response) => {
  try {
    if (!req.file) {
      res.status(400).json({ error: 'No file uploaded' });
      return;
    }
    // Return the relative URL that can be accessed via the static middleware
    // Note: The filename is generated by multer.config.ts
    const imageUrl = `/uploads/${req.file.filename}`;
    res.status(200).json({ imageUrl });
  } catch (error) {
    console.error('File upload error:', error);
    res.status(500).json({ error: 'Image upload failed' });
  }
};
